### ISSUE TITLE
allow ussd commands

### ISSUE THREAD

**Issue by johba37** [37coins/android-gateway#11]
Can invoke USSD commands (dialing codes ending in #), for example to check your phone's airtime balance, top-up, or transfer credit

**Comment by Gateway85** [comment]
still relevant?

**Comment by VonIobro** [comment]
I don't think this is relevant any more maybe could be moved to an idea on
the portfolio board.

On Wed, Jun 24, 2015 at 7:36 PM, Miriam <notifications@github.com> wrote:

> still relevant?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/37coins/android-gateway/issues/11#issuecomment-114819461>
> .
>



-- 
Jonathan Zobro
(+1) 617-294-9375

**Comment by Gateway85** [comment]
Hi Jonathan, 
Please go ahead to put it somewhere else and close the issue afterwards. 

Thanks, 
Miriam

**Comment by zobroj** [comment]
Moved info to this card on the portfolio board and closing:
