### ISSUE TITLE
Load Screen interrupted by Timeout

### ISSUE THREAD

**Issue by johba37** [37coins/android-gateway#22]
**Status**: When the internet connection is very slow, the modal dialog appears even though the app is loading.
**Desired**: If possible, even though it takes minutes, the app should finish loading.

**Tasks**:
- implement a a deterministic test for internet connectivity
  - set load timeout like this: http://stackoverflow.com/a/13310149/2067462
  - measure web-view load progress using [this call](http://developer.android.com/reference/android/webkit/WebView.html#getProgress%28%29)
- display web-view load progress as %-number on splash screen
- use timeout-timer, show modal dialog if web-view load progress didn't change for more than 20 seconds.

**Comment by dmitrycrocodilys** [comment]
Algo of page loading:
1. WebView sends 'progress' value. (we have no instruments to affect on it)
2. if web-view load progress didn't change for more than 20 seconds, show ...

the only thing we can do is to increase timeout value
