### ISSUE TITLE
Disconnected Phone Confirmation Page

### ISSUE THREAD

**Issue by v6** [37coins/android-gateway#27]
The phone number confirmation page, in which one is to enter a phone number to receive a confirming call for the gateway, does not respond. 

After one enters a number and submits it with the "Start Verification" button, the page refreshes, and, from that point onward, every minute or so a warning about a timeout will come up. 

No numbers entered result in a call back from the server. 

Perhaps I have already entered one of the numbers I attempted to use, but I think this issue may go deeper.

**Comment by johba37** [comment]
i've fixed this recently on the web by requiring the libPhoneNumber.js lib before rendering the view.
